export type MerchantStatus = "in_network" | "prospect" | "pending"

export type AffiliateMerchant = {
  id: string
  name: string
  category: string
  address: string
  city: string
  state: string
  zip: string
  posSystem: string
  status: MerchantStatus
  estimatedValue: number
  reward: number
  monthlyTransactions: number
  /** ISO date string, only set when status === "in_network". */
  signedUpAt?: string
  /** Affiliate handle credited with the signup. */
  signedUpBy?: string
  contactEmail?: string
  contactPhone?: string
  notes?: string
}

export const affiliateMerchants: AffiliateMerchant[] = [
  {
    id: "mer_001",
    name: "Sunrise Coffee Co.",
    category: "Coffee Shop",
    address: "123 Main Street",
    city: "San Francisco",
    state: "CA",
    zip: "94105",
    posSystem: "Square",
    status: "in_network",
    estimatedValue: 4800,
    reward: 240,
    monthlyTransactions: 3200,
    signedUpAt: "2026-03-12",
    signedUpBy: "you",
    contactEmail: "hello@sunrisecoffee.com",
    contactPhone: "(415) 555-0123",
  },
  {
    id: "mer_002",
    name: "Bay Bites Burgers",
    category: "Quick Service Restaurant",
    address: "742 Embarcadero",
    city: "San Francisco",
    state: "CA",
    zip: "94111",
    posSystem: "Toast",
    status: "prospect",
    estimatedValue: 7200,
    reward: 360,
    monthlyTransactions: 5400,
    contactEmail: "owner@baybitesburgers.com",
    contactPhone: "(415) 555-0188",
    notes: "Owner expressed interest at the May SF food expo. Follow up next week.",
  },
  {
    id: "mer_003",
    name: "Northgate Books",
    category: "Specialty Retail",
    address: "1290 Solano Ave",
    city: "Berkeley",
    state: "CA",
    zip: "94706",
    posSystem: "Lightspeed",
    status: "prospect",
    estimatedValue: 2400,
    reward: 120,
    monthlyTransactions: 1100,
    contactEmail: "manager@northgatebooks.com",
  },
  {
    id: "mer_004",
    name: "Pacific Pet Supply",
    category: "Specialty Retail",
    address: "55 Marina Blvd",
    city: "San Francisco",
    state: "CA",
    zip: "94123",
    posSystem: "Square",
    status: "pending",
    estimatedValue: 3600,
    reward: 180,
    monthlyTransactions: 2150,
    contactEmail: "info@pacificpet.com",
    notes: "Signed onboarding agreement — waiting on POS technician to finish install.",
  },
  {
    id: "mer_005",
    name: "Highline Wine Bar",
    category: "Bar & Lounge",
    address: "412 Hayes Street",
    city: "San Francisco",
    state: "CA",
    zip: "94102",
    posSystem: "Clover",
    status: "in_network",
    estimatedValue: 5400,
    reward: 270,
    monthlyTransactions: 2900,
    signedUpAt: "2026-02-04",
    signedUpBy: "you",
    contactEmail: "team@highlinewine.com",
  },
  {
    id: "mer_006",
    name: "Cedar & Stone Yoga",
    category: "Health & Fitness",
    address: "318 Valencia St",
    city: "San Francisco",
    state: "CA",
    zip: "94103",
    posSystem: "Mindbody",
    status: "prospect",
    estimatedValue: 1800,
    reward: 90,
    monthlyTransactions: 720,
    contactEmail: "studio@cedarstoneyoga.com",
  },
  {
    id: "mer_007",
    name: "Mission Hardware",
    category: "Home & Hardware",
    address: "2401 Mission St",
    city: "San Francisco",
    state: "CA",
    zip: "94110",
    posSystem: "Square",
    status: "prospect",
    estimatedValue: 6000,
    reward: 300,
    monthlyTransactions: 3800,
    contactEmail: "frontdesk@missionhardware.com",
    notes: "Family-owned for 32 years. Decision-maker is the owner's daughter.",
  },
  {
    id: "mer_008",
    name: "Foglight Florist",
    category: "Specialty Retail",
    address: "1872 Polk St",
    city: "San Francisco",
    state: "CA",
    zip: "94109",
    posSystem: "Shopify POS",
    status: "in_network",
    estimatedValue: 2100,
    reward: 105,
    monthlyTransactions: 980,
    signedUpAt: "2026-04-22",
    signedUpBy: "you",
    contactEmail: "orders@foglightflorist.com",
  },
  {
    id: "mer_009",
    name: "Golden Gate Bagels",
    category: "Bakery & Cafe",
    address: "2210 Chestnut St",
    city: "San Francisco",
    state: "CA",
    zip: "94123",
    posSystem: "Square",
    status: "in_network",
    estimatedValue: 3900,
    reward: 195,
    monthlyTransactions: 4200,
    signedUpAt: "2026-01-18",
    signedUpBy: "you",
    contactEmail: "hello@goldengatebagels.com",
    contactPhone: "(415) 555-0144",
  },
  {
    id: "mer_010",
    name: "Presidio Cycle Works",
    category: "Specialty Retail",
    address: "3650 Lombard St",
    city: "San Francisco",
    state: "CA",
    zip: "94123",
    posSystem: "Lightspeed",
    status: "prospect",
    estimatedValue: 5200,
    reward: 260,
    monthlyTransactions: 620,
    contactEmail: "shop@presidiocycle.com",
    notes: "High AOV — average ticket near $850. Strong fit for itemized digital receipts.",
  },
  {
    id: "mer_011",
    name: "Saltwater Sushi",
    category: "Full Service Restaurant",
    address: "1145 Folsom St",
    city: "San Francisco",
    state: "CA",
    zip: "94103",
    posSystem: "Toast",
    status: "in_network",
    estimatedValue: 9600,
    reward: 480,
    monthlyTransactions: 4100,
    signedUpAt: "2025-12-02",
    signedUpBy: "you",
    contactEmail: "info@saltwatersushi.com",
  },
  {
    id: "mer_012",
    name: "Twin Peaks Tap House",
    category: "Bar & Lounge",
    address: "501 Castro St",
    city: "San Francisco",
    state: "CA",
    zip: "94114",
    posSystem: "Toast",
    status: "pending",
    estimatedValue: 7800,
    reward: 390,
    monthlyTransactions: 3850,
    contactEmail: "ops@twinpeakstap.com",
    notes: "Awaiting Toast plugin install — scheduled for Friday.",
  },
  {
    id: "mer_013",
    name: "Marina Nail Studio",
    category: "Beauty & Personal Care",
    address: "2241 Union St",
    city: "San Francisco",
    state: "CA",
    zip: "94123",
    posSystem: "Square",
    status: "prospect",
    estimatedValue: 1500,
    reward: 75,
    monthlyTransactions: 880,
    contactEmail: "appointments@marinanail.com",
  },
  {
    id: "mer_014",
    name: "Outer Sunset Surf Co.",
    category: "Specialty Retail",
    address: "3877 Noriega St",
    city: "San Francisco",
    state: "CA",
    zip: "94122",
    posSystem: "Shopify POS",
    status: "prospect",
    estimatedValue: 3300,
    reward: 165,
    monthlyTransactions: 540,
    contactEmail: "shop@outersunsetsurf.com",
    notes: "Seasonal — peak from May to September.",
  },
  {
    id: "mer_015",
    name: "Pueblo Mexican Kitchen",
    category: "Full Service Restaurant",
    address: "2350 Telegraph Ave",
    city: "Oakland",
    state: "CA",
    zip: "94612",
    posSystem: "Clover",
    status: "in_network",
    estimatedValue: 6900,
    reward: 345,
    monthlyTransactions: 3650,
    signedUpAt: "2026-03-28",
    signedUpBy: "you",
    contactEmail: "manager@pueblokitchen.com",
  },
  {
    id: "mer_016",
    name: "Rockridge Grocers",
    category: "Grocery",
    address: "5655 College Ave",
    city: "Oakland",
    state: "CA",
    zip: "94618",
    posSystem: "NCR Aloha",
    status: "prospect",
    estimatedValue: 12400,
    reward: 620,
    monthlyTransactions: 9200,
    contactEmail: "hq@rockridgegrocers.com",
    notes: "Three locations — interested in a chain-wide rollout.",
  },
  {
    id: "mer_017",
    name: "Lakeshore Laundromat",
    category: "Personal Services",
    address: "3300 Lakeshore Ave",
    city: "Oakland",
    state: "CA",
    zip: "94610",
    posSystem: "Clover",
    status: "prospect",
    estimatedValue: 900,
    reward: 45,
    monthlyTransactions: 1400,
    contactEmail: "owner@lakeshorelaundromat.com",
  },
  {
    id: "mer_018",
    name: "Berkeley Bean Roasters",
    category: "Coffee Shop",
    address: "2519 Durant Ave",
    city: "Berkeley",
    state: "CA",
    zip: "94704",
    posSystem: "Square",
    status: "in_network",
    estimatedValue: 4200,
    reward: 210,
    monthlyTransactions: 3500,
    signedUpAt: "2026-02-19",
    signedUpBy: "you",
    contactEmail: "hello@berkeleybean.com",
  },
  {
    id: "mer_019",
    name: "El Cerrito Auto Spa",
    category: "Automotive Services",
    address: "11200 San Pablo Ave",
    city: "El Cerrito",
    state: "CA",
    zip: "94530",
    posSystem: "Clover",
    status: "prospect",
    estimatedValue: 2700,
    reward: 135,
    monthlyTransactions: 1200,
    contactEmail: "service@elcerritoauto.com",
  },
  {
    id: "mer_020",
    name: "Sausalito Sailing Club",
    category: "Recreation & Leisure",
    address: "100 Bay St",
    city: "Sausalito",
    state: "CA",
    zip: "94965",
    posSystem: "Square",
    status: "pending",
    estimatedValue: 4500,
    reward: 225,
    monthlyTransactions: 410,
    contactEmail: "membership@sausalitosail.com",
    notes: "Membership renewals coming up — wants receipts ready before July.",
  },
  {
    id: "mer_021",
    name: "Mill Valley Mercantile",
    category: "Specialty Retail",
    address: "87 Throckmorton Ave",
    city: "Mill Valley",
    state: "CA",
    zip: "94941",
    posSystem: "Shopify POS",
    status: "in_network",
    estimatedValue: 3000,
    reward: 150,
    monthlyTransactions: 1400,
    signedUpAt: "2026-04-08",
    signedUpBy: "you",
    contactEmail: "hello@mvmercantile.com",
  },
  {
    id: "mer_022",
    name: "Tiburon Tea House",
    category: "Coffee Shop",
    address: "1 Main St",
    city: "Tiburon",
    state: "CA",
    zip: "94920",
    posSystem: "Square",
    status: "prospect",
    estimatedValue: 2200,
    reward: 110,
    monthlyTransactions: 1800,
    contactEmail: "tea@tiburonteahouse.com",
  },
  {
    id: "mer_023",
    name: "Palo Alto Bike Shop",
    category: "Specialty Retail",
    address: "171 University Ave",
    city: "Palo Alto",
    state: "CA",
    zip: "94301",
    posSystem: "Lightspeed",
    status: "in_network",
    estimatedValue: 8400,
    reward: 420,
    monthlyTransactions: 720,
    signedUpAt: "2025-11-14",
    signedUpBy: "you",
    contactEmail: "ride@paloaltobike.com",
  },
  {
    id: "mer_024",
    name: "Stanford Stationery",
    category: "Specialty Retail",
    address: "459 Stanford Shopping Center",
    city: "Palo Alto",
    state: "CA",
    zip: "94304",
    posSystem: "Square",
    status: "prospect",
    estimatedValue: 1900,
    reward: 95,
    monthlyTransactions: 1100,
    contactEmail: "store@stanfordstationery.com",
  },
  {
    id: "mer_025",
    name: "Menlo Park Pharmacy",
    category: "Health & Wellness",
    address: "770 Santa Cruz Ave",
    city: "Menlo Park",
    state: "CA",
    zip: "94025",
    posSystem: "NCR Counterpoint",
    status: "pending",
    estimatedValue: 11600,
    reward: 580,
    monthlyTransactions: 7400,
    contactEmail: "manager@menloparkrx.com",
    notes: "Compliance review with their pharmacy software vendor in progress.",
  },
  {
    id: "mer_026",
    name: "Mountain View Mochi",
    category: "Bakery & Cafe",
    address: "215 Castro St",
    city: "Mountain View",
    state: "CA",
    zip: "94041",
    posSystem: "Square",
    status: "in_network",
    estimatedValue: 2700,
    reward: 135,
    monthlyTransactions: 2100,
    signedUpAt: "2026-04-30",
    signedUpBy: "you",
    contactEmail: "info@mvmochi.com",
  },
  {
    id: "mer_027",
    name: "Sunnyvale Smoke BBQ",
    category: "Full Service Restaurant",
    address: "210 S Murphy Ave",
    city: "Sunnyvale",
    state: "CA",
    zip: "94086",
    posSystem: "Toast",
    status: "prospect",
    estimatedValue: 8800,
    reward: 440,
    monthlyTransactions: 4600,
    contactEmail: "pitmaster@sunnyvalesmoke.com",
    notes: "Wants per-item allergen data on digital receipts.",
  },
  {
    id: "mer_028",
    name: "San Jose Sneaker Lab",
    category: "Specialty Retail",
    address: "78 S Market St",
    city: "San Jose",
    state: "CA",
    zip: "95113",
    posSystem: "Shopify POS",
    status: "prospect",
    estimatedValue: 5100,
    reward: 255,
    monthlyTransactions: 780,
    contactEmail: "sales@sjsneakerlab.com",
  },
  {
    id: "mer_029",
    name: "Willow Glen Wine Cellar",
    category: "Bar & Lounge",
    address: "1185 Lincoln Ave",
    city: "San Jose",
    state: "CA",
    zip: "95125",
    posSystem: "Clover",
    status: "in_network",
    estimatedValue: 4200,
    reward: 210,
    monthlyTransactions: 1850,
    signedUpAt: "2026-01-05",
    signedUpBy: "you",
    contactEmail: "cellar@willowglenwine.com",
  },
  {
    id: "mer_030",
    name: "Santa Cruz Surfboard Co.",
    category: "Specialty Retail",
    address: "415 Pacific Ave",
    city: "Santa Cruz",
    state: "CA",
    zip: "95060",
    posSystem: "Lightspeed",
    status: "prospect",
    estimatedValue: 4800,
    reward: 240,
    monthlyTransactions: 420,
    contactEmail: "shop@scsurfboards.com",
    notes: "Open to integration but waiting until end of summer season.",
  },
  {
    id: "mer_031",
    name: "Capitola Creamery",
    category: "Bakery & Cafe",
    address: "115 Monterey Ave",
    city: "Capitola",
    state: "CA",
    zip: "95010",
    posSystem: "Square",
    status: "in_network",
    estimatedValue: 2400,
    reward: 120,
    monthlyTransactions: 2600,
    signedUpAt: "2026-03-17",
    signedUpBy: "you",
    contactEmail: "scoops@capitolacreamery.com",
  },
  {
    id: "mer_032",
    name: "Monterey Bay Outfitters",
    category: "Specialty Retail",
    address: "303 Alvarado St",
    city: "Monterey",
    state: "CA",
    zip: "93940",
    posSystem: "Lightspeed",
    status: "prospect",
    estimatedValue: 6300,
    reward: 315,
    monthlyTransactions: 920,
    contactEmail: "outfit@montereybayoutfitters.com",
  },
  {
    id: "mer_033",
    name: "Carmel Pottery Studio",
    category: "Specialty Retail",
    address: "Dolores St btw 5th & 6th",
    city: "Carmel-by-the-Sea",
    state: "CA",
    zip: "93921",
    posSystem: "Square",
    status: "pending",
    estimatedValue: 1700,
    reward: 85,
    monthlyTransactions: 380,
    contactEmail: "studio@carmelpottery.com",
  },
  {
    id: "mer_034",
    name: "Napa Olive Press",
    category: "Specialty Retail",
    address: "835 Charter Oak Ave",
    city: "St. Helena",
    state: "CA",
    zip: "94574",
    posSystem: "Shopify POS",
    status: "in_network",
    estimatedValue: 5700,
    reward: 285,
    monthlyTransactions: 1100,
    signedUpAt: "2025-10-22",
    signedUpBy: "you",
    contactEmail: "oil@napaolive.com",
  },
  {
    id: "mer_035",
    name: "Sonoma Cheesemonger",
    category: "Grocery",
    address: "21 Matheson St",
    city: "Healdsburg",
    state: "CA",
    zip: "95448",
    posSystem: "Square",
    status: "prospect",
    estimatedValue: 4500,
    reward: 225,
    monthlyTransactions: 2200,
    contactEmail: "info@sonomacheesemonger.com",
    notes: "Tasting event scheduled — good time to demo Vero.",
  },
  {
    id: "mer_036",
    name: "Tahoe Trailhead Outfitters",
    category: "Specialty Retail",
    address: "850 Emerald Bay Rd",
    city: "South Lake Tahoe",
    state: "CA",
    zip: "96150",
    posSystem: "Lightspeed",
    status: "prospect",
    estimatedValue: 7200,
    reward: 360,
    monthlyTransactions: 1500,
    contactEmail: "gear@tahoetrailhead.com",
  },
  {
    id: "mer_037",
    name: "Sacramento Soul Kitchen",
    category: "Full Service Restaurant",
    address: "1131 K St",
    city: "Sacramento",
    state: "CA",
    zip: "95814",
    posSystem: "Toast",
    status: "in_network",
    estimatedValue: 8100,
    reward: 405,
    monthlyTransactions: 3900,
    signedUpAt: "2026-02-11",
    signedUpBy: "you",
    contactEmail: "kitchen@sacsoul.com",
  },
  {
    id: "mer_038",
    name: "Davis Co-op Market",
    category: "Grocery",
    address: "620 G St",
    city: "Davis",
    state: "CA",
    zip: "95616",
    posSystem: "NCR Counterpoint",
    status: "pending",
    estimatedValue: 13800,
    reward: 690,
    monthlyTransactions: 11200,
    contactEmail: "board@daviscoop.com",
    notes: "Board approved pilot — IT scheduling rollout for Q3.",
  },
  {
    id: "mer_039",
    name: "Folsom Family Diner",
    category: "Full Service Restaurant",
    address: "905 Sutter St",
    city: "Folsom",
    state: "CA",
    zip: "95630",
    posSystem: "Clover",
    status: "prospect",
    estimatedValue: 5400,
    reward: 270,
    monthlyTransactions: 4200,
    contactEmail: "frontofhouse@folsomdiner.com",
  },
  {
    id: "mer_040",
    name: "Roseville Razor Barbershop",
    category: "Beauty & Personal Care",
    address: "316 Vernon St",
    city: "Roseville",
    state: "CA",
    zip: "95678",
    posSystem: "Square",
    status: "in_network",
    estimatedValue: 1500,
    reward: 75,
    monthlyTransactions: 950,
    signedUpAt: "2026-04-15",
    signedUpBy: "you",
    contactEmail: "book@rosevillerazor.com",
  },
  {
    id: "mer_041",
    name: "Stockton Steakhouse",
    category: "Full Service Restaurant",
    address: "445 W Weber Ave",
    city: "Stockton",
    state: "CA",
    zip: "95203",
    posSystem: "Toast",
    status: "prospect",
    estimatedValue: 9300,
    reward: 465,
    monthlyTransactions: 2600,
    contactEmail: "reservations@stocktonsteak.com",
  },
  {
    id: "mer_042",
    name: "Modesto Music Exchange",
    category: "Specialty Retail",
    address: "1015 10th St",
    city: "Modesto",
    state: "CA",
    zip: "95354",
    posSystem: "Lightspeed",
    status: "prospect",
    estimatedValue: 2800,
    reward: 140,
    monthlyTransactions: 540,
    contactEmail: "trades@modestomusic.com",
  },
  {
    id: "mer_043",
    name: "Fresno Fruit Stand",
    category: "Grocery",
    address: "1234 Shaw Ave",
    city: "Fresno",
    state: "CA",
    zip: "93710",
    posSystem: "Square",
    status: "in_network",
    estimatedValue: 3300,
    reward: 165,
    monthlyTransactions: 3100,
    signedUpAt: "2026-01-29",
    signedUpBy: "you",
    contactEmail: "stand@fresnofruit.com",
  },
  {
    id: "mer_044",
    name: "Bakersfield Boots & Hats",
    category: "Specialty Retail",
    address: "2030 19th St",
    city: "Bakersfield",
    state: "CA",
    zip: "93301",
    posSystem: "Lightspeed",
    status: "prospect",
    estimatedValue: 4200,
    reward: 210,
    monthlyTransactions: 760,
    contactEmail: "shop@bakersfieldboots.com",
  },
  {
    id: "mer_045",
    name: "Santa Barbara Sandwich Shop",
    category: "Quick Service Restaurant",
    address: "514 State St",
    city: "Santa Barbara",
    state: "CA",
    zip: "93101",
    posSystem: "Square",
    status: "in_network",
    estimatedValue: 4600,
    reward: 230,
    monthlyTransactions: 3700,
    signedUpAt: "2025-12-15",
    signedUpBy: "you",
    contactEmail: "lunch@sbsandwich.com",
  },
  {
    id: "mer_046",
    name: "Venice Beach Boards",
    category: "Specialty Retail",
    address: "1410 Ocean Front Walk",
    city: "Venice",
    state: "CA",
    zip: "90291",
    posSystem: "Shopify POS",
    status: "pending",
    estimatedValue: 3900,
    reward: 195,
    monthlyTransactions: 680,
    contactEmail: "shop@venicebeachboards.com",
    notes: "Shopify POS plugin install scheduled for next Monday.",
  },
  {
    id: "mer_047",
    name: "Silver Lake Vinyl",
    category: "Specialty Retail",
    address: "2630 Hyperion Ave",
    city: "Los Angeles",
    state: "CA",
    zip: "90027",
    posSystem: "Square",
    status: "prospect",
    estimatedValue: 2700,
    reward: 135,
    monthlyTransactions: 900,
    contactEmail: "records@silverlakevinyl.com",
  },
  {
    id: "mer_048",
    name: "Pasadena Pottery & Plants",
    category: "Specialty Retail",
    address: "85 W Colorado Blvd",
    city: "Pasadena",
    state: "CA",
    zip: "91105",
    posSystem: "Shopify POS",
    status: "in_network",
    estimatedValue: 3000,
    reward: 150,
    monthlyTransactions: 1250,
    signedUpAt: "2026-03-04",
    signedUpBy: "you",
    contactEmail: "hello@pasadenapottery.com",
  },
  {
    id: "mer_049",
    name: "Long Beach Lobster Co.",
    category: "Full Service Restaurant",
    address: "5411 E 2nd St",
    city: "Long Beach",
    state: "CA",
    zip: "90803",
    posSystem: "Toast",
    status: "prospect",
    estimatedValue: 10500,
    reward: 525,
    monthlyTransactions: 4400,
    contactEmail: "events@longbeachlobster.com",
    notes: "Multi-location — interested in single-account rollout across three sites.",
  },
  {
    id: "mer_050",
    name: "San Diego Sun Smoothies",
    category: "Quick Service Restaurant",
    address: "3766 Mission Blvd",
    city: "San Diego",
    state: "CA",
    zip: "92109",
    posSystem: "Square",
    status: "in_network",
    estimatedValue: 3600,
    reward: 180,
    monthlyTransactions: 3300,
    signedUpAt: "2026-04-26",
    signedUpBy: "you",
    contactEmail: "blend@sdsunsmoothies.com",
  },
]

export function getMerchantById(id: string): AffiliateMerchant | undefined {
  return affiliateMerchants.find((m) => m.id === id)
}
